// --------------------------------------------------------------------------------------------------------------------
// <copyright company="" file="ValidationResource.Designer.cs">
//   
// </copyright>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <summary>
//   A strongly-typed resource class, for looking up localized strings, etc.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace GameStore.Web.Resouces {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class ValidationResource {
        /// <summary>
        /// The resource man.
        /// </summary>
        private static ResourceManager resourceMan;

        /// <summary>
        /// The resource culture.
        /// </summary>
        private static CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationResource"/> class.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("GameStore.Web.Resouces.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }
        

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }

            set {
                resourceCulture = value;
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Value of field &quot;{PropertyName}&quot; must be existent!.
        /// </summary>
        public static string Existent {
            get {
                return ResourceManager.GetString("Existent", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Value of field &quot;{PropertyName}&quot; must be greater of equal {ComparisonValue}!.
        /// </summary>
        public static string GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Length of &quot;{PropertyName}&quot; must be from {MinLength} to {MaxLength}!.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{PropertyName}&quot; is required!.
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Value of field &quot;{PropertyName}&quot; must be unique!.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
    }
}
