// <auto-generated />
namespace GameStore.DAL.GameStore.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class M1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M1));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261328056_M1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
